version: '3.8'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: api
      MONGO_INITDB_ROOT_PASSWORD: nosql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  mongo_data: